BEGIN;
CREATE TABLE `stats_address` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `street` varchar(100) NOT NULL, `city` varchar(50) NOT NULL, `state` varchar(2) NOT NULL, `zip_code` varchar(20) NOT NULL, `phone` varchar(20) NULL, `email` varchar(75) NULL);
CREATE TABLE `stats_card` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `minute` smallint NOT NULL, `color` varchar(1) NOT NULL);
CREATE TABLE `stats_club` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `short_name` varchar(3) NOT NULL, `logo` varchar(100) NOT NULL, `address_id` integer NULL);
CREATE TABLE `stats_coach` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY);
CREATE TABLE `stats_coachfor` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `from_date` date NOT NULL, `to_date` date NULL, `responsiblity` varchar(1) NOT NULL, `coach_id` integer NOT NULL);
CREATE TABLE `stats_competition` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `short_name` varchar(5) NOT NULL, `competition_type` varchar(1) NOT NULL, `belongs_id` integer NOT NULL);
CREATE TABLE `stats_field` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `address_id` integer NOT NULL);
CREATE TABLE `stats_game` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `date` date NOT NULL);
CREATE TABLE `stats_goal` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `minute` smallint NOT NULL);
CREATE TABLE `stats_person` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `first_name` varchar(50) NOT NULL, `middle_name` varchar(50) NOT NULL, `last_name` varchar(50) NOT NULL, `birthday` date NOT NULL, `gender` varchar(1) NOT NULL, `address_id` integer NULL);
CREATE TABLE `stats_player` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `person_id` integer NOT NULL);
CREATE TABLE `stats_playfor` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `from_date` date NOT NULL, `to_date` date NULL, `player_id` integer NOT NULL);
CREATE TABLE `stats_referee` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `person_id` integer NOT NULL);
CREATE TABLE `stats_season` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `start_date` date NOT NULL, `end_date` date NOT NULL);
CREATE TABLE `stats_suspension` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `date_received` date NOT NULL, `number_games` smallint NOT NULL, `suspended_until` date NOT NULL, `reason` varchar(1000) NOT NULL, `fine` smallint NOT NULL, `fine_paid` bool NOT NULL, `player_id` integer NOT NULL);
CREATE TABLE `stats_team` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `short_name` varchar(3) NOT NULL, `color_first` varchar(20) NOT NULL, `color_second` varchar(20) NOT NULL, `classification` varchar(5) NOT NULL, `club_id` integer NULL);
CREATE TABLE `stats_season_enrolled` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `season_id` integer NOT NULL, `team_id` integer NOT NULL, UNIQUE (`season_id`, `team_id`));
ALTER TABLE `stats_season` ADD COLUMN `of_id` integer NOT NULL;
ALTER TABLE `stats_season` ALTER COLUMN `of_id` DROP DEFAULT;
ALTER TABLE `stats_playfor` ADD COLUMN `team_id` integer NOT NULL;
ALTER TABLE `stats_playfor` ALTER COLUMN `team_id` DROP DEFAULT;
ALTER TABLE `stats_goal` ADD COLUMN `assisted_by_id` integer NULL;
ALTER TABLE `stats_goal` ALTER COLUMN `assisted_by_id` DROP DEFAULT;
ALTER TABLE `stats_goal` ADD COLUMN `scored_against_id` integer NOT NULL;
ALTER TABLE `stats_goal` ALTER COLUMN `scored_against_id` DROP DEFAULT;
ALTER TABLE `stats_goal` ADD COLUMN `scored_by_id` integer NOT NULL;
ALTER TABLE `stats_goal` ALTER COLUMN `scored_by_id` DROP DEFAULT;
ALTER TABLE `stats_goal` ADD COLUMN `scored_for_id` integer NOT NULL;
ALTER TABLE `stats_goal` ALTER COLUMN `scored_for_id` DROP DEFAULT;
ALTER TABLE `stats_goal` ADD COLUMN `scored_in_id` integer NOT NULL;
ALTER TABLE `stats_goal` ALTER COLUMN `scored_in_id` DROP DEFAULT;
ALTER TABLE `stats_game` ADD COLUMN `away_team_id` integer NOT NULL;
ALTER TABLE `stats_game` ALTER COLUMN `away_team_id` DROP DEFAULT;
ALTER TABLE `stats_game` ADD COLUMN `field_id` integer NOT NULL;
ALTER TABLE `stats_game` ALTER COLUMN `field_id` DROP DEFAULT;
ALTER TABLE `stats_game` ADD COLUMN `home_team_id` integer NOT NULL;
ALTER TABLE `stats_game` ALTER COLUMN `home_team_id` DROP DEFAULT;
ALTER TABLE `stats_game` ADD COLUMN `referee_id` integer NOT NULL;
ALTER TABLE `stats_game` ALTER COLUMN `referee_id` DROP DEFAULT;
ALTER TABLE `stats_game` ADD COLUMN `season_id` integer NOT NULL;
ALTER TABLE `stats_game` ALTER COLUMN `season_id` DROP DEFAULT;
ALTER TABLE `stats_coachfor` ADD COLUMN `team_id` integer NOT NULL;
ALTER TABLE `stats_coachfor` ALTER COLUMN `team_id` DROP DEFAULT;
ALTER TABLE `stats_coach` ADD COLUMN `person_id` integer NOT NULL;
ALTER TABLE `stats_coach` ALTER COLUMN `person_id` DROP DEFAULT;
ALTER TABLE `stats_card` ADD COLUMN `received_by_id` integer NOT NULL;
ALTER TABLE `stats_card` ALTER COLUMN `received_by_id` DROP DEFAULT;
ALTER TABLE `stats_card` ADD COLUMN `received_in_id` integer NOT NULL;
ALTER TABLE `stats_card` ALTER COLUMN `received_in_id` DROP DEFAULT;
CREATE INDEX stats_club_ea8e5d12 ON `stats_club` (`address_id`);
ALTER TABLE `stats_club` ADD CONSTRAINT stats_club_address_id_6846fe0254819089_fk_stats_address_id FOREIGN KEY (`address_id`) REFERENCES `stats_address` (`id`);
CREATE INDEX stats_coachfor_ea814e95 ON `stats_coachfor` (`coach_id`);
ALTER TABLE `stats_coachfor` ADD CONSTRAINT stats_coachfor_coach_id_41e4215015b93ccc_fk_stats_coach_id FOREIGN KEY (`coach_id`) REFERENCES `stats_coach` (`id`);
CREATE INDEX stats_competition_be7f5386 ON `stats_competition` (`belongs_id`);
ALTER TABLE `stats_competition` ADD CONSTRAINT stats_compet_belongs_id_734f027aa093d957_fk_stats_competition_id FOREIGN KEY (`belongs_id`) REFERENCES `stats_competition` (`id`);
CREATE INDEX stats_field_ea8e5d12 ON `stats_field` (`address_id`);
ALTER TABLE `stats_field` ADD CONSTRAINT stats_field_address_id_37ebfde016c42162_fk_stats_address_id FOREIGN KEY (`address_id`) REFERENCES `stats_address` (`id`);
CREATE INDEX stats_person_ea8e5d12 ON `stats_person` (`address_id`);
ALTER TABLE `stats_person` ADD CONSTRAINT stats_person_address_id_723582a4ef700afe_fk_stats_address_id FOREIGN KEY (`address_id`) REFERENCES `stats_address` (`id`);
CREATE INDEX stats_player_a8452ca7 ON `stats_player` (`person_id`);
ALTER TABLE `stats_player` ADD CONSTRAINT stats_player_person_id_321b1b86a96534cc_fk_stats_person_id FOREIGN KEY (`person_id`) REFERENCES `stats_person` (`id`);
CREATE INDEX stats_playfor_afe72417 ON `stats_playfor` (`player_id`);
ALTER TABLE `stats_playfor` ADD CONSTRAINT stats_playfor_player_id_3c0ca8cbf5129d3f_fk_stats_player_id FOREIGN KEY (`player_id`) REFERENCES `stats_player` (`id`);
CREATE INDEX stats_referee_a8452ca7 ON `stats_referee` (`person_id`);
ALTER TABLE `stats_referee` ADD CONSTRAINT stats_referee_person_id_6f8b3b6a22267f0a_fk_stats_person_id FOREIGN KEY (`person_id`) REFERENCES `stats_person` (`id`);
CREATE INDEX stats_suspension_afe72417 ON `stats_suspension` (`player_id`);
ALTER TABLE `stats_suspension` ADD CONSTRAINT stats_suspension_player_id_1e43e4fe392d9324_fk_stats_player_id FOREIGN KEY (`player_id`) REFERENCES `stats_player` (`id`);
CREATE INDEX stats_team_7115697a ON `stats_team` (`club_id`);
ALTER TABLE `stats_team` ADD CONSTRAINT stats_team_club_id_5837c0f04cf87d9f_fk_stats_club_id FOREIGN KEY (`club_id`) REFERENCES `stats_club` (`id`);
CREATE INDEX stats_season_enrolled_b11701f0 ON `stats_season_enrolled` (`season_id`);
ALTER TABLE `stats_season_enrolled` ADD CONSTRAINT stats_season_enrol_season_id_3f8228a1ca5434f1_fk_stats_season_id FOREIGN KEY (`season_id`) REFERENCES `stats_season` (`id`);
CREATE INDEX stats_season_enrolled_f6a7ca40 ON `stats_season_enrolled` (`team_id`);
ALTER TABLE `stats_season_enrolled` ADD CONSTRAINT stats_season_enrolled_team_id_42ef71903b77e6b7_fk_stats_team_id FOREIGN KEY (`team_id`) REFERENCES `stats_team` (`id`);
CREATE INDEX stats_season_5451f30c ON `stats_season` (`of_id`);
ALTER TABLE `stats_season` ADD CONSTRAINT stats_season_of_id_1fcf077ffff281c4_fk_stats_competition_id FOREIGN KEY (`of_id`) REFERENCES `stats_competition` (`id`);
CREATE INDEX stats_playfor_f6a7ca40 ON `stats_playfor` (`team_id`);
ALTER TABLE `stats_playfor` ADD CONSTRAINT stats_playfor_team_id_4302a18993221e1f_fk_stats_team_id FOREIGN KEY (`team_id`) REFERENCES `stats_team` (`id`);
CREATE INDEX stats_goal_fbf76cfd ON `stats_goal` (`assisted_by_id`);
ALTER TABLE `stats_goal` ADD CONSTRAINT stats_goal_assisted_by_id_7b7a804a2bc4ff80_fk_stats_player_id FOREIGN KEY (`assisted_by_id`) REFERENCES `stats_player` (`id`);
CREATE INDEX stats_goal_ca415070 ON `stats_goal` (`scored_against_id`);
ALTER TABLE `stats_goal` ADD CONSTRAINT stats_goal_scored_against_id_6a076a597cfdec7d_fk_stats_team_id FOREIGN KEY (`scored_against_id`) REFERENCES `stats_team` (`id`);
CREATE INDEX stats_goal_75a7163c ON `stats_goal` (`scored_by_id`);
ALTER TABLE `stats_goal` ADD CONSTRAINT stats_goal_scored_by_id_2dca7b348d791a96_fk_stats_player_id FOREIGN KEY (`scored_by_id`) REFERENCES `stats_player` (`id`);
CREATE INDEX stats_goal_cb446227 ON `stats_goal` (`scored_for_id`);
ALTER TABLE `stats_goal` ADD CONSTRAINT stats_goal_scored_for_id_db647aa03f2e9c7_fk_stats_team_id FOREIGN KEY (`scored_for_id`) REFERENCES `stats_team` (`id`);
CREATE INDEX stats_goal_8e9c7365 ON `stats_goal` (`scored_in_id`);
ALTER TABLE `stats_goal` ADD CONSTRAINT stats_goal_scored_in_id_30b3063107b66c64_fk_stats_game_id FOREIGN KEY (`scored_in_id`) REFERENCES `stats_game` (`id`);
CREATE INDEX stats_game_901b4047 ON `stats_game` (`away_team_id`);
ALTER TABLE `stats_game` ADD CONSTRAINT stats_game_away_team_id_30e966ad7cee71e1_fk_stats_team_id FOREIGN KEY (`away_team_id`) REFERENCES `stats_team` (`id`);
CREATE INDEX stats_game_3aabf39f ON `stats_game` (`field_id`);
ALTER TABLE `stats_game` ADD CONSTRAINT stats_game_field_id_7864b5a2584fd2b1_fk_stats_field_id FOREIGN KEY (`field_id`) REFERENCES `stats_field` (`id`);
CREATE INDEX stats_game_e5623f1e ON `stats_game` (`home_team_id`);
ALTER TABLE `stats_game` ADD CONSTRAINT stats_game_home_team_id_7bfd9c06946665f0_fk_stats_team_id FOREIGN KEY (`home_team_id`) REFERENCES `stats_team` (`id`);
CREATE INDEX stats_game_3cf09080 ON `stats_game` (`referee_id`);
ALTER TABLE `stats_game` ADD CONSTRAINT stats_game_referee_id_796ef95bea597d9_fk_stats_referee_id FOREIGN KEY (`referee_id`) REFERENCES `stats_referee` (`id`);
CREATE INDEX stats_game_b11701f0 ON `stats_game` (`season_id`);
ALTER TABLE `stats_game` ADD CONSTRAINT stats_game_season_id_6cda2aee8dcb0c2d_fk_stats_season_id FOREIGN KEY (`season_id`) REFERENCES `stats_season` (`id`);
CREATE INDEX stats_coachfor_f6a7ca40 ON `stats_coachfor` (`team_id`);
ALTER TABLE `stats_coachfor` ADD CONSTRAINT stats_coachfor_team_id_587d585348391910_fk_stats_team_id FOREIGN KEY (`team_id`) REFERENCES `stats_team` (`id`);
CREATE INDEX stats_coach_a8452ca7 ON `stats_coach` (`person_id`);
ALTER TABLE `stats_coach` ADD CONSTRAINT stats_coach_person_id_3bcd3e0b059cb78a_fk_stats_person_id FOREIGN KEY (`person_id`) REFERENCES `stats_person` (`id`);
CREATE INDEX stats_card_91fa5d21 ON `stats_card` (`received_by_id`);
ALTER TABLE `stats_card` ADD CONSTRAINT stats_card_received_by_id_72ea6a3017415efe_fk_stats_player_id FOREIGN KEY (`received_by_id`) REFERENCES `stats_player` (`id`);
CREATE INDEX stats_card_def6ee40 ON `stats_card` (`received_in_id`);
ALTER TABLE `stats_card` ADD CONSTRAINT stats_card_received_in_id_7ca52a4b070c1770_fk_stats_game_id FOREIGN KEY (`received_in_id`) REFERENCES `stats_game` (`id`);

COMMIT;
